spring.application.name=course_spring
server.port=5000
# configurar variaveis de banco de dados
# spring.datasource.url=""
# spring.datasource.username=root
# spring.datasource.password=root
spring.profiles.active=dev
